import Head from "next/head";
import styles from "@/styles/PAbout.module.scss";

// Components
import TPageUI from "@/components/TPageUI";
import OInfo from "@/components/OInfo";
import OGallery from "@/components/OGallery";
import OServices from "@/components/OServices";
import OSummary from "@/components/OSummary";
import TFrame from "@/components/TFrame";
import TTrack from "@/components/TTrack";


export default function About() {
    return (
        <>
            <Head>
                <title>Caroline Field</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/assets/logo-gold.svg" type="image/x-icon"></link>
                
                {/* <meta charSet="UTF-8"/> */}
                {/* <script type="module" defer src="./ts/main.ts"></script> */}
            </Head>

            <body>
                <TFrame />

                <main>

                    <section className={styles.Splash}>
                        <OInfo />
                        <OGallery />
                    </section>


                    {/* <TTrack> */}
                        <section>
                            <OServices />
                        </section>
                    {/* </TTrack> */}

                    <TTrack>
                        <TPageUI>
                            <OSummary />
                        </TPageUI>
                    </TTrack>


                </main>
            </body>
        </>
    );
}