import Head from "next/head";
import styles from "@/styles/PAbout.module.scss";
import { useState } from "react";

// Components
import TLayoutPage from "@/components/TLayoutPage";
import OInfo from "@/components/OInfo";
import OGallery from "@/components/OGallery";
import OServices from "@/components/OServices";
import OSummary from "@/components/OSummary";
import TFrame from "@/components/TFrame";
import TTrack from "@/components/TTrack";
import MNav from "@/components/MNav";
import MCredits from "@/components/MCredits";

// FIXME
import { Geist_Mono } from "next/font/google";

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export default function About() {
    const [trackProgress, setTrackProgress] = useState(0);

    // useEffect(() => {
    //     debugger;
    // }, []);

    return (
        <>
            <Head>
                <title>Caroline Field</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/assets/logo-gold.svg" type="image/x-icon"></link>
                <meta charSet="UTF-8" />
                {/* FIXME */}
                <link rel="stylesheet" href="https://use.typekit.net/kyn8apf.css" />
                {/* <script type="module" defer src="./ts/main.ts"></script> */}
            </Head>

            <body className={styles.About}>
                <TFrame 
                    cropFrame={trackProgress} 
                    showTexture={trackProgress == 100} 
                    showShadow={trackProgress == 100} 
                />

                <main className={`${geistMono.variable}`}>

                    <section className={styles.About__splash}>
                        <OInfo />
                        <OGallery />
                    </section>

                    <section>
                        <OServices />
                    </section>

                    <TTrack setProgress={setTrackProgress}>
                        <TLayoutPage
                            header={<MNav showNav={trackProgress == 100} />}
                            body={<OSummary />}
                            footer={<MCredits />}
                        />
                    </TTrack>

                </main>
            </body>
        </>
    );
}