import Head from "next/head";
import styles from "@/styles/PAbout.module.scss";
import { useState } from "react";

// Components
import TLayoutPage from "@/components/TLayoutPage";
import OInfo from "@/components/OInfo";
import OGallery from "@/components/OGallery";
import OServices from "@/components/OServices";
import OSummary from "@/components/OSummary";
import TFrame from "@/components/TFrame";
import TTrack from "@/components/TTrack";
import MNav from "@/components/MNav";
import MCredits from "@/components/MCredits";


export default function About() {
    const [showNav, setShowNav] = useState(true);
    const [cropFrame, setCropFrame] = useState(0);

    return (
        <>
            <Head>
                <title>Caroline Field</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/assets/logo-gold.svg" type="image/x-icon"></link>

                {/* <meta charSet="UTF-8"/> */}
                {/* <script type="module" defer src="./ts/main.ts"></script> */}
            </Head>

            <body>
                <TFrame cropFrame={cropFrame} />

                <main>
                    <section className={styles.Splash}>
                        <OInfo />
                        <OGallery />
                    </section>

                    <section>
                        <OServices />
                    </section>

                    <TTrack setShowNav={setShowNav} setCropFrame={setCropFrame}>
                        <section className={styles.Splash}>
                            <TLayoutPage
                                header={<MNav showNav={showNav} />}
                                body={<OSummary />}
                                footer={<MCredits />}
                            />
                        </section>
                    </TTrack>
                </main>
            </body>
        </>
    );
}